Fixed Size[] used on tensors (#96)
The error AttributeError: 'Tensor' object has no attribute 'Size' is caused by the incorrect usage of Size[] instead of the correct method size().