Fixed Size[] used on tensors (#96) (#98)
The error AttributeError: 'Tensor' object has no attribute 'Size' is caused by the incorrect usage of Size[] instead of the correct method size().

Co-authored-by: Dávid Gajdoš <50640452+davidgajdos1@users.noreply.github.com>